name: "Sync"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      PROJECT_URL: ${{ secrets.PROJECT_URL }}
      SERVICE_ROLE: ${{ secrets.SERVICE_ROLE }}

      SRC_REMOTE_URL: https://x-access-token:${{ secrets.SRC_REPO_TOKEN }}@github.com/arnottferels/${{ secrets.SRC_REPO_NAME }}.git
      SRC_REPO_DIR: src

      PUBLIC_DIR: data/public

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5

      - name: Set timestamp
        run: echo "TIMESTAMP=$(date '+%Y-%m-%d %H:%M')" >> $GITHUB_ENV

      - name: Clone source repo, run scripts, and commit there
        run: |
          set -e
          git clone $SRC_REMOTE_URL $SRC_REPO_DIR
          cd $SRC_REPO_DIR

          npm ci
          npm run all

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update $TIMESTAMP"
            git push origin main
          fi
          cd ..

      - name: Copy public data from source to root
        run: |
          set -e
          cp -a "$SRC_REPO_DIR/$PUBLIC_DIR/." ./
          rm -rf "$SRC_REPO_DIR"

      - name: Commit and push public data in this repo
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          if git diff --cached --quiet; then
            echo "No changes in public data to commit"
          else
            git commit -m "Update $TIMESTAMP"
            git push origin main
          fi
